// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Money_Tracker.Models;

#nullable disable

namespace Money_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230319005124_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Money_Tracker.Models.Categoria", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaId"), 1L, 1);

                    b.Property<string>("categoriaIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("categoriaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("categoriaTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("categoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Money_Tracker.Models.Transaccion", b =>
                {
                    b.Property<int>("transaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transaccionId"), 1L, 1);

                    b.Property<int>("categoriaID")
                        .HasColumnType("int");

                    b.Property<string>("transaccionDescripcion")
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime>("transaccionFecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("transaccionMonto")
                        .HasColumnType("int");

                    b.HasKey("transaccionId");

                    b.HasIndex("categoriaID");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("Money_Tracker.Models.Transaccion", b =>
                {
                    b.HasOne("Money_Tracker.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
